pub const Air = @import("compile/Air.zig");
pub const Parser = @import("compile/parse/Parser.zig");
pub const Runtime = @import("emulate/Runtime.zig");
pub const Debugger = @import("emulate/debugger/Debugger.zig");
pub const Traps = @import("Traps.zig");
pub const Policies = @import("policies.zig").Policies;
pub const reporting = @import("reporting/reporting.zig");

test {
    const refAllDecls = @import("std").testing.refAllDecls;
    refAllDecls(@import("root.zig"));
    refAllDecls(@import("compile/Operand.zig"));
    refAllDecls(@import("compile/Span.zig"));
    refAllDecls(@import("compile/instruction.zig"));
    refAllDecls(@import("compile/Air.zig"));
    refAllDecls(@import("compile/parse/parsing.zig"));
    refAllDecls(@import("compile/parse/case.zig"));
    refAllDecls(@import("compile/parse/Tokenizer.zig"));
    refAllDecls(@import("compile/parse/Lexer.zig"));
    refAllDecls(@import("compile/parse/Parser.zig"));
    refAllDecls(@import("compile/parse/integers.zig"));
    refAllDecls(@import("compile/parse/Token.zig"));
    refAllDecls(@import("callback.zig"));
    refAllDecls(@import("reporting/Ctx.zig"));
    refAllDecls(@import("reporting/diagnostic.zig"));
    refAllDecls(@import("reporting/reporting.zig"));
    refAllDecls(@import("policies.zig"));
    refAllDecls(@import("Traps.zig"));
    refAllDecls(@import("emulate/decode.zig"));
    refAllDecls(@import("emulate/Tty.zig"));
    refAllDecls(@import("emulate/builtin_traps.zig"));
    refAllDecls(@import("emulate/Bitmask.zig"));
    refAllDecls(@import("emulate/debugger/Command.zig"));
    refAllDecls(@import("emulate/debugger/Breakpoints.zig"));
    refAllDecls(@import("emulate/debugger/editor/Editor.zig"));
    refAllDecls(@import("emulate/debugger/editor/History.zig"));
    refAllDecls(@import("emulate/debugger/editor/Live.zig"));
    refAllDecls(@import("emulate/debugger/tags.zig"));
    refAllDecls(@import("emulate/debugger/Input.zig"));
    refAllDecls(@import("emulate/debugger/Debugger.zig"));
    refAllDecls(@import("emulate/debugger/parse.zig"));
    refAllDecls(@import("emulate/Runtime.zig"));
}
